### ISSUE TITLE
Adicionar Tecnologias utilizadas no README

### ISSUE THREAD

**Issue by eduardosoareszup** [luantoningalvan/ancaphub#61]
Seguindo o que foi dito na issue #52 e fazendo um breve complemento. Seria interessante colocar logo no início quais as principais tecnologias e `frameworks` utilizados na criação da plataforma. Isso facilitaria com que outros usuário possam identificar a melhor forma de contribuição.

**Comment by eduardosoareszup** [comment]
Vocês utilizam `React` e `Node` né?

**Comment by HenriqueFutema** [comment]
Sim!
