### ISSUE TITLE
Criação de um ROADMAP

### ISSUE THREAD

**Issue by eduardosoareszup** [luantoningalvan/ancaphub#62]
Vi que o projeto pretende ter inúmeras funcionalidades, algumas mais simples e outras mais complexas. Acredito que o legal seria ter um **Roadmap** para podermos ver como está o andamento e em que parte podemos ajudar. E também fazer um estudo de lançar a plataforma sem ter todas as funcionalidades prontas, porque isso pode demorar um certo tempo.

Complementando o Roadmap, seria legal já deixar várias tarefas quebradas lá nos `Projects` vi que já tem algumas lá, mas estão todas prontas kk. Tendo algumas em TODO facilita para quem vem de fora saber a partir de onde já se pode contribuir. 

![image](https://user-images.githubusercontent.com/47856493/80417058-875c9c00-88ab-11ea-9dd4-2d0bd7b55925.png)

**Comment by luantoningalvan** [comment]
Iremos organizar essa parte
