### ISSUE TITLE
Padronizar o uso do Eslint 

### ISSUE THREAD

**Issue by gustavorodarte** [luantoningalvan/ancaphub#63]
O projeto do Client contem eslint, mas o Dashboard e server não. Isso está causando inconsistências graves no estilo de codigo do projeto.

A idea é discutir qual seria o padrão do eslint deve ser adotado, minha sugestão é o do airbnb.

**Comment by andreqramos** [comment]
Olá, Gustavo! Cara, penso da mesma forma. O padrão mais usado atualmente é o do airbnb. Inclusive, o standart estava apresentando alguns conflitos com o Prettier, mas o do airbnb não.

**Comment by luantoningalvan** [comment]
Iremos fazer esta padronização!
