### ISSUE TITLE
Upload de arquivos está sendo feita de forma ineficiente. 

### ISSUE THREAD

**Issue by gustavorodarte** [luantoningalvan/ancaphub#64]
A estratégia utilizada é ineficiente, está sendo enviado todo o arquivo para o backend que envia para o bucket do s3.  Isso gera um trafico de dados desnecessário e um maior tempo de resposta da requisição. 

Uma estrategia melhor seria a de uso de pre-signed urls, onde o client requisita uma para o backend. E utilizando ela faz o upload direto para o bucket, assim não se precisa enviar o arquivo para o backend. 

Um pouco mais sobre isso na docs da AWS:

https://docs.aws.amazon.com/pt_br/AmazonS3/latest/dev/PresignedUrlUploadObject.html

**Comment by luantoningalvan** [comment]
Todo sistema de upload será refeito utilizando essa estratégia, obrigado por citar!
