### ISSUE TITLE
Side Efects não estão sendo isolados em alguns componentes

### ISSUE THREAD

**Issue by gustavorodarte** [luantoningalvan/ancaphub#65]
Nos seguintes componentes do dashbord: chooseCategory, fileUpload, e imageUpload, estão sendo feitas request asyncronas diretamente do componente, em vez de ser isolado em thunks.

**Comment by luantoningalvan** [comment]
Este repositório não conta mais com o dashboard. O mesmo foi movido para:[github.com/ancaphub/ancaphub-dashboard](url)
