### ISSUE TITLE
Verificação do Token JWT está duplicada em varias rotas.

### ISSUE THREAD

**Issue by gustavorodarte** [luantoningalvan/ancaphub#67]
No projeto já tem um middleware que decodifica  o token e adiciona as info do user no objeto req. Porem mesmo assim está se utilizando inumeras vezes o `server/src/utils/verifyToken.js`  para conseguir as informações  do usario, sendo que a mesma já pode ser acessada pelo objeto req.

**Comment by luantoningalvan** [comment]
O nosso sistema de autenticação será refeito considerando este ponto, obrigado por citar!
