### ISSUE TITLE
Sugestão de stack. 

### ISSUE THREAD

**Issue by MichelDiz** [luantoningalvan/ancaphub#70]
Adicionem GraphQL, Dgraph, Apollo Client(GraphQL) ao projeto..

Pontos a considerar:

1. GraphQL é muito melhor que REST.
2. Dgraph é muito melhor que mongo (document based DB). É um DB criado para ser distribuído, escalonável e rápido. Sem falar que é Graph. Relacionamentos de entidades são milhões de vezes mais simples que SQL ou Mongo. 
3. E o Dgraph já vem com GraphQL embutido, basta montar o esquema que vc economiza 80% em seu Bussines Logic e libs de terceiros. Literalmente Dgraph faz 80% do trabalho que vc precisaria fazer ao configurar um servidor GraphQL padrão. Só precisa aprender GraphQL e o basico de Dgraph.
4. Docker, Docker-compose com Dgraph e GraphQL é easy peasy, lemon squeezy.
5. Eu posso guia-los e contribuir com as bases e fazer sugestões (Eu trabalho para a Dgraph, teria muito pouco tempo pra dedicar, mas garanto que vale a pena Dgraph é muito bom).

**Comment by luantoningalvan** [comment]
O momento atual e o objetivo de entrega não nos permitem alterar a stack. Talvez em um futuro isso seja plausível.
