### ISSUE TITLE
Feedback para o usuário em caso de erro validação

### ISSUE THREAD

**Issue by kibutzzz** [luantoningalvan/ancaphub#75]
Fui testar a aplicação e logo na pagina de cadastro de conta tive alguns problemas:
Ao preencher o formulario de cadastro e submete-lo, a aplicação da nenhum retorno ao usuário.

Coloquei um console.log na validação do formulario e descobri que era esse o problema.

Seria bom implementar (ou corrigir caso isso já devesse estar acontecendo) alguma forma de mostrar ao usuario quais são os erros que ele cometeu no preenchimento do formulario

Segue a imagem do erro: 
![image](https://user-images.githubusercontent.com/29122454/81973188-25fe3200-95fa-11ea-996d-745003cc7cd1.png)

**Comment by luantoningalvan** [comment]
Todos os erros estão vindo do backend, iremos implementar um sistema que alerte o usuário quando isso acontecer.
