### ISSUE TITLE
[Bug] Ao entrar em perfil pessoal são exibidas publicações do último perfil visitado

### ISSUE THREAD

**Issue by luantoningalvan** [luantoningalvan/ancaphub#78]
*Browser:* Chrome 81.0.4044.138
*OS:* Windows 10.0
*Screen:* 1366x768
*Viewport:* 1366x629

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/cky5z4qhkv3bjt55yb6z/b74mtywcfh01d50jvzf5/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTE5NzcxNTgsImRhdGEiOnsicmVwb3J0IjoiYjc0bXR5d2NmaDAxZDUwanZ6ZjUiLCJ1c2VyIjoiR2l0SHViIn19.jnSXnm4b6uJxw5bSAPokzu3gmMnhxPqW7c16psG8bqg)

**Comment by paulo-santana** [comment]
Esse bug é no backend mesmo? Numa investigação inicial, eu vi que quando você clica no perfil de alguém, ele manda uma requisição com o ID do perfil em questão pro servidor. Daí quando você clica no botão do seu próprio perfil, ele manda a mesma requisição e mantém o ID do perfil que você tava visitando.

Eu manjo bem pouco de reactjs. então achei meio complicado rastrear esse erro no repositório de frontend

Edit: Agora que vi que é um sistema de report automático
